version: '3.8'

services:
  sveltekit:
    build:
      context: .
      args:
        VITE_REDIRECT_URI: ${VITE_REDIRECT_URI}
        VITE_GITHUB_CLIENT_SECRET: ${VITE_GITHUB_CLIENT_SECRET}
        VITE_GITHUB_CLIENT_ID: ${VITE_GITHUB_CLIENT_ID}
        VITE_ADMIN_EMAIL: ${VITE_ADMIN_EMAIL}
    container_name: sveltekit-app
    expose:
      - "3000"
    volumes:
      - ./prisma:/app/prisma
    environment:
      - NODE_ENV=production
    env_file:
      - .env

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - sveltekit

volumes:
  caddy_data:
  caddy_config:
